--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 15.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ic_aportes_semanales; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ic_aportes_semanales (
    id_aporte uuid DEFAULT gen_random_uuid() NOT NULL,
    id_socio text NOT NULL,
    monto numeric(10,2) NOT NULL,
    fecha date NOT NULL,
    comprobante_url text,
    id_usuario_registro uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.ic_aportes_semanales OWNER TO postgres;

--
-- Name: TABLE ic_aportes_semanales; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.ic_aportes_semanales IS 'Esquema actualizado para aportes';


--
-- Name: ic_bancos_logos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ic_bancos_logos (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    bancos text NOT NULL,
    imagenes text
);


ALTER TABLE public.ic_bancos_logos OWNER TO postgres;

--
-- Name: ic_bancos_logos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ic_bancos_logos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ic_bancos_logos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ic_contratos; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.ic_contratos (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    fecha_contrato date NOT NULL,
    parte_contrato text NOT NULL,
    nombre_razon text NOT NULL,
    cedula_ruc text NOT NULL,
    pais text NOT NULL,
    detalle text NOT NULL,
    monto numeric(15,2) NOT NULL,
    frecuencia text NOT NULL,
    cantidad_duracion integer NOT NULL,
    fecha_fin date NOT NULL,
    url_foto text,
    estado text DEFAULT 'ACTIVO'::text,
    creado_por uuid,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.ic_contratos OWNER TO supabase_admin;

--
-- Name: ic_creditos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ic_creditos (
    id_credito uuid DEFAULT gen_random_uuid() NOT NULL,
    id_socio text NOT NULL,
    id_solicitud text,
    codigo_credito text NOT NULL,
    capital numeric(12,2) NOT NULL,
    gastos_administrativos numeric(10,2) DEFAULT 0 NOT NULL,
    capital_financiado numeric(12,2) GENERATED ALWAYS AS ((capital + gastos_administrativos)) STORED,
    tasa_interes_mensual numeric(5,2) NOT NULL,
    total_interes numeric(12,2) DEFAULT 0 NOT NULL,
    total_dias integer DEFAULT 0 NOT NULL,
    plazo integer NOT NULL,
    dia_pago integer NOT NULL,
    cuota_base numeric(10,2) NOT NULL,
    ahorro_programado_cuota numeric(10,2) DEFAULT 0 NOT NULL,
    ahorro_programado_total numeric(12,2) DEFAULT 0 NOT NULL,
    cuota_con_ahorro numeric(10,2) NOT NULL,
    fecha_desembolso date NOT NULL,
    fecha_base date NOT NULL,
    fecha_primer_pago date NOT NULL,
    fecha_fin_credito date NOT NULL,
    estado_credito text DEFAULT 'PENDIENTE'::text NOT NULL,
    cuotas_pagadas integer DEFAULT 0 NOT NULL,
    cuotas_en_mora integer DEFAULT 0 NOT NULL,
    documentos_generados boolean DEFAULT false NOT NULL,
    creado_por uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    observaciones text,
    garante boolean DEFAULT false,
    CONSTRAINT ic_creditos_capital_check CHECK ((capital > (0)::numeric)),
    CONSTRAINT ic_creditos_dia_pago_check CHECK ((dia_pago = ANY (ARRAY[10, 15, 20]))),
    CONSTRAINT ic_creditos_estado_credito_check CHECK ((estado_credito = ANY (ARRAY['PENDIENTE'::text, 'ACTIVO'::text, 'MOROSO'::text, 'CANCELADO'::text, 'PRECANCELADO'::text, 'PAUSADO'::text, 'RECHAZADO'::text]))),
    CONSTRAINT ic_creditos_plazo_check CHECK ((plazo > 0)),
    CONSTRAINT ic_creditos_tasa_interes_mensual_check CHECK ((tasa_interes_mensual > (0)::numeric))
);


ALTER TABLE public.ic_creditos OWNER TO postgres;

--
-- Name: TABLE ic_creditos; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.ic_creditos IS 'Tabla principal de créditos otorgados';


--
-- Name: COLUMN ic_creditos.capital_financiado; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.ic_creditos.capital_financiado IS 'Capital + gastos administrativos (calculado)';


--
-- Name: COLUMN ic_creditos.dia_pago; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.ic_creditos.dia_pago IS 'Solo permite 10, 15 o 20 de cada mes';


--
-- Name: ic_creditos_ahorro; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ic_creditos_ahorro (
    id_ahorro uuid DEFAULT gen_random_uuid() NOT NULL,
    id_credito uuid NOT NULL,
    id_detalle uuid,
    numero_cuota integer NOT NULL,
    monto numeric(10,2) NOT NULL,
    estado text DEFAULT 'PENDIENTE'::text NOT NULL,
    fecha_devolucion date,
    monto_devuelto numeric(10,2),
    observacion text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    CONSTRAINT ic_creditos_ahorro_estado_check CHECK ((estado = ANY (ARRAY['PENDIENTE'::text, 'ACUMULADO'::text, 'DEVUELTO'::text, 'RETENIDO'::text])))
);


ALTER TABLE public.ic_creditos_ahorro OWNER TO postgres;

--
-- Name: TABLE ic_creditos_ahorro; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.ic_creditos_ahorro IS 'Registro detallado del ahorro programado por cuota';


--
-- Name: ic_creditos_amortizacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ic_creditos_amortizacion (
    id_detalle uuid DEFAULT gen_random_uuid() NOT NULL,
    id_credito uuid NOT NULL,
    numero_cuota integer NOT NULL,
    fecha_vencimiento date NOT NULL,
    dias_periodo integer DEFAULT 30 NOT NULL,
    pago_capital numeric(10,2) NOT NULL,
    pago_interes numeric(10,2) NOT NULL,
    pago_gastos_admin numeric(10,2) DEFAULT 0 NOT NULL,
    cuota_base numeric(10,2) NOT NULL,
    ahorro_programado numeric(10,2) DEFAULT 0 NOT NULL,
    cuota_total numeric(10,2) NOT NULL,
    saldo_capital numeric(12,2) NOT NULL,
    estado_cuota text DEFAULT 'PENDIENTE'::text NOT NULL,
    requiere_cobro boolean DEFAULT true NOT NULL,
    recordatorio_enviado boolean DEFAULT false NOT NULL,
    fecha_ultimo_recordatorio timestamp with time zone,
    intentos_cobro integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    recordatorio_hoy boolean DEFAULT false NOT NULL,
    CONSTRAINT ic_creditos_amortizacion_estado_cuota_check CHECK ((estado_cuota = ANY (ARRAY['PENDIENTE'::text, 'PAGADO'::text, 'PARCIAL'::text, 'VENCIDO'::text, 'PAUSADO'::text, 'CONDONADO'::text]))),
    CONSTRAINT ic_creditos_amortizacion_numero_cuota_check CHECK ((numero_cuota > 0))
);


ALTER TABLE public.ic_creditos_amortizacion OWNER TO postgres;

--
-- Name: TABLE ic_creditos_amortizacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.ic_creditos_amortizacion IS 'Tabla de amortización - detalle de cada cuota';


--
-- Name: ic_creditos_documentos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ic_creditos_documentos (
    id_documento uuid DEFAULT gen_random_uuid() NOT NULL,
    id_credito uuid NOT NULL,
    contrato_generado boolean DEFAULT false NOT NULL,
    contrato_firmado boolean DEFAULT false NOT NULL,
    contrato_url text,
    pagare_generado boolean DEFAULT false NOT NULL,
    pagare_firmado boolean DEFAULT false NOT NULL,
    pagare_url text,
    tabla_amortizacion_generada boolean DEFAULT false NOT NULL,
    tabla_amortizacion_firmada boolean DEFAULT false NOT NULL,
    tabla_amortizacion_url text,
    documento_garante_firmado boolean DEFAULT false NOT NULL,
    documento_garante_url text,
    fecha_firma_contrato date,
    fecha_firma_pagare date,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone
);


ALTER TABLE public.ic_creditos_documentos OWNER TO postgres;

--
-- Name: TABLE ic_creditos_documentos; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.ic_creditos_documentos IS 'Control de documentos generados y firmados del crédito';


--
-- Name: ic_creditos_garantes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ic_creditos_garantes (
    id_garante uuid DEFAULT gen_random_uuid() NOT NULL,
    id_credito uuid NOT NULL,
    nombre_garante text NOT NULL,
    cedula_garante text NOT NULL,
    domicilio_garante text,
    telefono_garante text,
    whatsapp_garante text,
    foto_cedula_url text,
    foto_domicilio_url text,
    firma_url text,
    documentos_completos boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone
);


ALTER TABLE public.ic_creditos_garantes OWNER TO postgres;

--
-- Name: TABLE ic_creditos_garantes; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.ic_creditos_garantes IS 'Garantes asociados a cada crédito (puede haber varios)';


--
-- Name: ic_creditos_historial; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ic_creditos_historial (
    id_historial uuid DEFAULT gen_random_uuid() NOT NULL,
    id_credito uuid NOT NULL,
    estado_anterior text NOT NULL,
    estado_nuevo text NOT NULL,
    fecha_cambio timestamp with time zone DEFAULT now() NOT NULL,
    usuario uuid,
    motivo text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.ic_creditos_historial OWNER TO postgres;

--
-- Name: TABLE ic_creditos_historial; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.ic_creditos_historial IS 'Historial de cambios de estado del crédito';


--
-- Name: ic_creditos_pagos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ic_creditos_pagos (
    id_pago uuid DEFAULT gen_random_uuid() NOT NULL,
    id_detalle uuid NOT NULL,
    id_credito uuid NOT NULL,
    fecha_pago date NOT NULL,
    monto_pagado numeric(10,2) NOT NULL,
    metodo_pago text DEFAULT 'EFECTIVO'::text NOT NULL,
    referencia_pago text,
    comprobante_url text,
    cobrado_por uuid,
    fecha_registro timestamp with time zone DEFAULT now() NOT NULL,
    observaciones text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ic_creditos_pagos_metodo_pago_check CHECK ((metodo_pago = ANY (ARRAY['EFECTIVO'::text, 'TRANSFERENCIA'::text, 'DEPOSITO'::text, 'CHEQUE'::text, 'OTRO'::text]))),
    CONSTRAINT ic_creditos_pagos_monto_pagado_check CHECK ((monto_pagado > (0)::numeric))
);


ALTER TABLE public.ic_creditos_pagos OWNER TO postgres;

--
-- Name: TABLE ic_creditos_pagos; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.ic_creditos_pagos IS 'Registro de todos los pagos realizados';


--
-- Name: ic_creditos_precancelacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ic_creditos_precancelacion (
    id_precancelacion uuid DEFAULT gen_random_uuid() NOT NULL,
    id_credito uuid NOT NULL,
    fecha_precancelacion date NOT NULL,
    cuotas_pagadas integer NOT NULL,
    cuotas_restantes integer NOT NULL,
    capital_pendiente numeric(12,2) NOT NULL,
    dias_desde_ultima_cuota integer DEFAULT 0 NOT NULL,
    interes_proporcional numeric(10,2) DEFAULT 0 NOT NULL,
    interes_perdonado numeric(10,2) DEFAULT 0 NOT NULL,
    ahorro_acumulado numeric(10,2) DEFAULT 0 NOT NULL,
    ahorro_devuelto numeric(10,2) DEFAULT 0 NOT NULL,
    monto_precancelacion numeric(12,2) NOT NULL,
    comprobante_url text,
    procesado_por uuid,
    observacion text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.ic_creditos_precancelacion OWNER TO postgres;

--
-- Name: TABLE ic_creditos_precancelacion; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.ic_creditos_precancelacion IS 'Registro de precancelaciones de créditos';


--
-- Name: ic_gastos_administrativos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ic_gastos_administrativos (
    id_gastos text NOT NULL,
    monto numeric(10,2) NOT NULL,
    motivo text NOT NULL,
    fecha date NOT NULL,
    inicio date,
    fotografia text,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT monto_positivo CHECK ((monto >= (0)::numeric))
);


ALTER TABLE public.ic_gastos_administrativos OWNER TO postgres;

--
-- Name: ic_polizas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ic_polizas (
    id_poliza uuid DEFAULT gen_random_uuid() NOT NULL,
    id_socio text NOT NULL,
    fecha date DEFAULT CURRENT_DATE NOT NULL,
    valor numeric(12,2) NOT NULL,
    interes numeric(5,2) NOT NULL,
    plazo integer NOT NULL,
    fecha_vencimiento date NOT NULL,
    valor_final numeric(12,2) NOT NULL,
    valor_en_letras text,
    valor_final_en_letras text,
    certificado_firmado text,
    estado text DEFAULT 'ACTIVO'::text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    notas text
);


ALTER TABLE public.ic_polizas OWNER TO postgres;

--
-- Name: ic_polizas_pagos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ic_polizas_pagos (
    id_pago_poliza uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
    id_poliza uuid,
    id_socio text,
    monto_total_pagado numeric(15,2) NOT NULL,
    monto_capital numeric(15,2) DEFAULT 0,
    monto_interes numeric(15,2) DEFAULT 0,
    fecha_pago timestamp with time zone DEFAULT now(),
    tipo_pago text NOT NULL,
    metodo_pago text DEFAULT 'TRANSFERENCIA'::text,
    notas text,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.ic_polizas_pagos OWNER TO postgres;

--
-- Name: TABLE ic_polizas_pagos; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.ic_polizas_pagos IS 'Registro histórico de desembolsos realizados a los inversionistas de pólizas';


--
-- Name: COLUMN ic_polizas_pagos.tipo_pago; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.ic_polizas_pagos.tipo_pago IS 'Si es LIQUIDACION_TOTAL significa que la póliza se cerró y el socio llevó todo. PAGO_INTERES_RENOVACION es cuando se renueva solo el capital.';


--
-- Name: ic_preferencial; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ic_preferencial (
    idcredito text NOT NULL,
    idsocio text,
    tipo text NOT NULL,
    fechasolicitud text,
    fechaaprobacion text,
    porcentaje text,
    motivo text,
    monto text,
    montofinal text,
    nombrebeneficiario text,
    estado text,
    fotografia text,
    motivorespuesta text,
    motivorecargo text,
    idmensajejose text,
    idmensajehenry text,
    whatsappbeneficiario text,
    created_at timestamp with time zone DEFAULT now(),
    valor_abonado numeric DEFAULT 0.00,
    CONSTRAINT ic_preferencial_estado_check CHECK ((estado = ANY (ARRAY['APROBADO'::text, 'RECHAZADO'::text, 'DESEMBOLSADO'::text, 'ABONADO'::text, 'PAGADO'::text, 'PENDIENTE'::text]))),
    CONSTRAINT ic_preferencial_tipo_check CHECK ((tipo = ANY (ARRAY['ESTUDIANTIL'::text, 'SALUD'::text, 'PREFERENCIAL'::text, 'POR DEFINIR'::text, 'PAGO'::text, 'RECHAZADO'::text])))
);


ALTER TABLE public.ic_preferencial OWNER TO postgres;

--
-- Name: ic_services; Type: TABLE; Schema: public; Owner: supabase_admin
--

CREATE TABLE public.ic_services (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    instance text,
    apikey text
);


ALTER TABLE public.ic_services OWNER TO supabase_admin;

--
-- Name: ic_services_id_seq; Type: SEQUENCE; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.ic_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ic_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ic_situacion_bancaria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ic_situacion_bancaria (
    id_transaccion text NOT NULL,
    nombre_banco text NOT NULL,
    tipo_transaccion text,
    plazo_tipo text,
    plazo integer,
    valor numeric(12,2),
    interes numeric(5,2),
    monto_final numeric(12,2),
    contador integer,
    fecha_transaccion date,
    primer_pago date,
    mensual numeric(10,2),
    estado text DEFAULT 'ACTIVO'::text,
    valor_descontado numeric(12,2),
    a_nombre_de text,
    motivo text,
    logo_banco text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone
);


ALTER TABLE public.ic_situacion_bancaria OWNER TO postgres;

--
-- Name: ic_situacion_bancaria_detalle; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ic_situacion_bancaria_detalle (
    id_detalle text NOT NULL,
    transaccion text NOT NULL,
    cuota integer NOT NULL,
    valor numeric(10,2),
    estado text DEFAULT 'PENDIENTE'::text,
    fecha_pago date,
    fecha_pagado date,
    fotografia text,
    enviar_pdf text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone
);


ALTER TABLE public.ic_situacion_bancaria_detalle OWNER TO postgres;

--
-- Name: ic_socios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ic_socios (
    idsocio text NOT NULL,
    nombre text,
    cedula text,
    domicilio text,
    fotoidentidad text,
    fotodomicilio text,
    whatsapp bigint,
    paisresidencia text,
    estadocivil text,
    nombrereferencia text,
    whatsappreferencia bigint,
    whatsappconyuge text,
    nombreconyuge text,
    cedulaconyuge text,
    fotodocumentoconyuge text,
    bien text,
    fotobien text,
    firmaconyuge text,
    fotofirma text,
    tipo text,
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.ic_socios OWNER TO postgres;

--
-- Name: ic_solicitud_de_credito; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ic_solicitud_de_credito (
    solicitudid text NOT NULL,
    nombresocio text,
    cedulasocio text,
    direccionsocio text,
    fotodireccion text,
    fotoidentidad text,
    whatsappsocio text,
    paisresidencia text,
    estadocivil text,
    nombreconyuge text,
    paisresidenciaconyuge text,
    whatsappconyuge text,
    fotoidentidadconyuge text,
    nombrereferencia text,
    whatsappreferencia text,
    fotoidentidadreferencia text,
    bien text,
    fotobien text,
    fotofirma text,
    fotofirmaconyuge text,
    monto numeric(12,2),
    fotoconid text,
    estado text,
    created_by uuid NOT NULL,
    cedulaconyuge text,
    plazo smallint DEFAULT '12'::smallint
);


ALTER TABLE public.ic_solicitud_de_credito OWNER TO postgres;

--
-- Name: ic_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ic_users (
    id uuid NOT NULL,
    nombre text NOT NULL,
    correo text NOT NULL,
    whatsapp text,
    rol text DEFAULT 'usuario'::text NOT NULL,
    activo boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    cedula text,
    lugar_asesor text
);


ALTER TABLE public.ic_users OWNER TO postgres;

--
-- Name: ic_aportes_semanales ic_aportes_semanales_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_aportes_semanales
    ADD CONSTRAINT ic_aportes_semanales_pkey PRIMARY KEY (id_aporte);


--
-- Name: ic_bancos_logos ic_bancos_logos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_bancos_logos
    ADD CONSTRAINT ic_bancos_logos_pkey PRIMARY KEY (id);


--
-- Name: ic_contratos ic_contratos_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.ic_contratos
    ADD CONSTRAINT ic_contratos_pkey PRIMARY KEY (id);


--
-- Name: ic_creditos_ahorro ic_creditos_ahorro_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos_ahorro
    ADD CONSTRAINT ic_creditos_ahorro_pkey PRIMARY KEY (id_ahorro);


--
-- Name: ic_creditos_amortizacion ic_creditos_amortizacion_id_credito_numero_cuota_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos_amortizacion
    ADD CONSTRAINT ic_creditos_amortizacion_id_credito_numero_cuota_key UNIQUE (id_credito, numero_cuota);


--
-- Name: ic_creditos_amortizacion ic_creditos_amortizacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos_amortizacion
    ADD CONSTRAINT ic_creditos_amortizacion_pkey PRIMARY KEY (id_detalle);


--
-- Name: ic_creditos ic_creditos_codigo_credito_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos
    ADD CONSTRAINT ic_creditos_codigo_credito_key UNIQUE (codigo_credito);


--
-- Name: ic_creditos_documentos ic_creditos_documentos_id_credito_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos_documentos
    ADD CONSTRAINT ic_creditos_documentos_id_credito_key UNIQUE (id_credito);


--
-- Name: ic_creditos_documentos ic_creditos_documentos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos_documentos
    ADD CONSTRAINT ic_creditos_documentos_pkey PRIMARY KEY (id_documento);


--
-- Name: ic_creditos_garantes ic_creditos_garantes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos_garantes
    ADD CONSTRAINT ic_creditos_garantes_pkey PRIMARY KEY (id_garante);


--
-- Name: ic_creditos_historial ic_creditos_historial_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos_historial
    ADD CONSTRAINT ic_creditos_historial_pkey PRIMARY KEY (id_historial);


--
-- Name: ic_creditos_pagos ic_creditos_pagos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos_pagos
    ADD CONSTRAINT ic_creditos_pagos_pkey PRIMARY KEY (id_pago);


--
-- Name: ic_creditos ic_creditos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos
    ADD CONSTRAINT ic_creditos_pkey PRIMARY KEY (id_credito);


--
-- Name: ic_creditos_precancelacion ic_creditos_precancelacion_id_credito_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos_precancelacion
    ADD CONSTRAINT ic_creditos_precancelacion_id_credito_key UNIQUE (id_credito);


--
-- Name: ic_creditos_precancelacion ic_creditos_precancelacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos_precancelacion
    ADD CONSTRAINT ic_creditos_precancelacion_pkey PRIMARY KEY (id_precancelacion);


--
-- Name: ic_gastos_administrativos ic_gastos_administrativos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_gastos_administrativos
    ADD CONSTRAINT ic_gastos_administrativos_pkey PRIMARY KEY (id_gastos);


--
-- Name: ic_polizas_pagos ic_polizas_pagos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_polizas_pagos
    ADD CONSTRAINT ic_polizas_pagos_pkey PRIMARY KEY (id_pago_poliza);


--
-- Name: ic_polizas ic_polizas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_polizas
    ADD CONSTRAINT ic_polizas_pkey PRIMARY KEY (id_poliza);


--
-- Name: ic_preferencial ic_preferencial_idcredito_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_preferencial
    ADD CONSTRAINT ic_preferencial_idcredito_key UNIQUE (idcredito);


--
-- Name: ic_preferencial ic_preferencial_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_preferencial
    ADD CONSTRAINT ic_preferencial_pkey PRIMARY KEY (idcredito);


--
-- Name: ic_services ic_services_pkey; Type: CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.ic_services
    ADD CONSTRAINT ic_services_pkey PRIMARY KEY (id);


--
-- Name: ic_situacion_bancaria_detalle ic_situacion_bancaria_detalle_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_situacion_bancaria_detalle
    ADD CONSTRAINT ic_situacion_bancaria_detalle_pkey PRIMARY KEY (id_detalle);


--
-- Name: ic_situacion_bancaria ic_situacion_bancaria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_situacion_bancaria
    ADD CONSTRAINT ic_situacion_bancaria_pkey PRIMARY KEY (id_transaccion);


--
-- Name: ic_socios ic_socios_cedula_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_socios
    ADD CONSTRAINT ic_socios_cedula_key UNIQUE (cedula);


--
-- Name: ic_socios ic_socios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_socios
    ADD CONSTRAINT ic_socios_pkey PRIMARY KEY (idsocio);


--
-- Name: ic_solicitud_de_credito ic_solicitud_de_credito_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_solicitud_de_credito
    ADD CONSTRAINT ic_solicitud_de_credito_pkey PRIMARY KEY (solicitudid);


--
-- Name: ic_users ic_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_users
    ADD CONSTRAINT ic_users_pkey PRIMARY KEY (id);


--
-- Name: idx_amortizacion_credito; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_amortizacion_credito ON public.ic_creditos_amortizacion USING btree (id_credito);


--
-- Name: idx_amortizacion_estado; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_amortizacion_estado ON public.ic_creditos_amortizacion USING btree (estado_cuota);


--
-- Name: idx_amortizacion_vencimiento; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_amortizacion_vencimiento ON public.ic_creditos_amortizacion USING btree (fecha_vencimiento);


--
-- Name: idx_creditos_codigo; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_creditos_codigo ON public.ic_creditos USING btree (codigo_credito);


--
-- Name: idx_creditos_estado; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_creditos_estado ON public.ic_creditos USING btree (estado_credito);


--
-- Name: idx_creditos_socio; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_creditos_socio ON public.ic_creditos USING btree (id_socio);


--
-- Name: idx_creditos_solicitud; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_creditos_solicitud ON public.ic_creditos USING btree (id_solicitud);


--
-- Name: idx_gastos_fecha; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_gastos_fecha ON public.ic_gastos_administrativos USING btree (fecha DESC);


--
-- Name: idx_gastos_motivo_simple; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_gastos_motivo_simple ON public.ic_gastos_administrativos USING btree (motivo);


--
-- Name: idx_historial_credito; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_historial_credito ON public.ic_creditos_historial USING btree (id_credito);


--
-- Name: idx_pagos_cobrado_por; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pagos_cobrado_por ON public.ic_creditos_pagos USING btree (cobrado_por);


--
-- Name: idx_pagos_credito; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pagos_credito ON public.ic_creditos_pagos USING btree (id_credito);


--
-- Name: idx_pagos_detalle; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pagos_detalle ON public.ic_creditos_pagos USING btree (id_detalle);


--
-- Name: idx_pagos_fecha; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pagos_fecha ON public.ic_creditos_pagos USING btree (fecha_pago);


--
-- Name: idx_polizas_pagos_id_poliza; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_polizas_pagos_id_poliza ON public.ic_polizas_pagos USING btree (id_poliza);


--
-- Name: idx_polizas_pagos_id_socio; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_polizas_pagos_id_socio ON public.ic_polizas_pagos USING btree (id_socio);


--
-- Name: idx_situacion_bancaria_detalle_transaccion; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_situacion_bancaria_detalle_transaccion ON public.ic_situacion_bancaria_detalle USING btree (transaccion);


--
-- Name: ic_creditos_pagos trg_sync_amortizacion_status; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_sync_amortizacion_status AFTER INSERT OR DELETE OR UPDATE ON public.ic_creditos_pagos FOR EACH ROW EXECUTE FUNCTION public.fn_sync_amortizacion_status();


--
-- Name: ic_creditos_amortizacion trg_sync_credito_master_status; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_sync_credito_master_status AFTER UPDATE OF estado_cuota ON public.ic_creditos_amortizacion FOR EACH ROW EXECUTE FUNCTION public.fn_sync_credito_master_status();


--
-- Name: ic_contratos update_ic_contratos_updated_at; Type: TRIGGER; Schema: public; Owner: supabase_admin
--

CREATE TRIGGER update_ic_contratos_updated_at BEFORE UPDATE ON public.ic_contratos FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: ic_creditos_ahorro update_ic_creditos_ahorro_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_ic_creditos_ahorro_updated_at BEFORE UPDATE ON public.ic_creditos_ahorro FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: ic_creditos_amortizacion update_ic_creditos_amortizacion_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_ic_creditos_amortizacion_updated_at BEFORE UPDATE ON public.ic_creditos_amortizacion FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: ic_creditos_documentos update_ic_creditos_documentos_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_ic_creditos_documentos_updated_at BEFORE UPDATE ON public.ic_creditos_documentos FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: ic_creditos_garantes update_ic_creditos_garantes_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_ic_creditos_garantes_updated_at BEFORE UPDATE ON public.ic_creditos_garantes FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: ic_creditos update_ic_creditos_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_ic_creditos_updated_at BEFORE UPDATE ON public.ic_creditos FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: ic_aportes_semanales ic_aportes_semanales_id_socio_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_aportes_semanales
    ADD CONSTRAINT ic_aportes_semanales_id_socio_fkey FOREIGN KEY (id_socio) REFERENCES public.ic_socios(idsocio) ON DELETE RESTRICT;


--
-- Name: ic_contratos ic_contratos_creado_por_fkey; Type: FK CONSTRAINT; Schema: public; Owner: supabase_admin
--

ALTER TABLE ONLY public.ic_contratos
    ADD CONSTRAINT ic_contratos_creado_por_fkey FOREIGN KEY (creado_por) REFERENCES public.ic_users(id) ON DELETE SET NULL;


--
-- Name: ic_creditos_ahorro ic_creditos_ahorro_id_credito_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos_ahorro
    ADD CONSTRAINT ic_creditos_ahorro_id_credito_fkey FOREIGN KEY (id_credito) REFERENCES public.ic_creditos(id_credito) ON DELETE CASCADE;


--
-- Name: ic_creditos_amortizacion ic_creditos_amortizacion_id_credito_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos_amortizacion
    ADD CONSTRAINT ic_creditos_amortizacion_id_credito_fkey FOREIGN KEY (id_credito) REFERENCES public.ic_creditos(id_credito) ON DELETE CASCADE;


--
-- Name: ic_creditos_documentos ic_creditos_documentos_id_credito_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos_documentos
    ADD CONSTRAINT ic_creditos_documentos_id_credito_fkey FOREIGN KEY (id_credito) REFERENCES public.ic_creditos(id_credito) ON DELETE CASCADE;


--
-- Name: ic_creditos_garantes ic_creditos_garantes_id_credito_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos_garantes
    ADD CONSTRAINT ic_creditos_garantes_id_credito_fkey FOREIGN KEY (id_credito) REFERENCES public.ic_creditos(id_credito) ON DELETE CASCADE;


--
-- Name: ic_creditos_historial ic_creditos_historial_id_credito_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos_historial
    ADD CONSTRAINT ic_creditos_historial_id_credito_fkey FOREIGN KEY (id_credito) REFERENCES public.ic_creditos(id_credito) ON DELETE CASCADE;


--
-- Name: ic_creditos ic_creditos_id_socio_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos
    ADD CONSTRAINT ic_creditos_id_socio_fkey FOREIGN KEY (id_socio) REFERENCES public.ic_socios(idsocio) ON DELETE RESTRICT;


--
-- Name: ic_creditos_pagos ic_creditos_pagos_cobrado_por_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos_pagos
    ADD CONSTRAINT ic_creditos_pagos_cobrado_por_fkey FOREIGN KEY (cobrado_por) REFERENCES public.ic_users(id) ON DELETE SET NULL;


--
-- Name: ic_creditos_pagos ic_creditos_pagos_id_credito_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos_pagos
    ADD CONSTRAINT ic_creditos_pagos_id_credito_fkey FOREIGN KEY (id_credito) REFERENCES public.ic_creditos(id_credito) ON DELETE CASCADE;


--
-- Name: ic_creditos_pagos ic_creditos_pagos_id_detalle_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos_pagos
    ADD CONSTRAINT ic_creditos_pagos_id_detalle_fkey FOREIGN KEY (id_detalle) REFERENCES public.ic_creditos_amortizacion(id_detalle) ON DELETE RESTRICT;


--
-- Name: ic_creditos_precancelacion ic_creditos_precancelacion_id_credito_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_creditos_precancelacion
    ADD CONSTRAINT ic_creditos_precancelacion_id_credito_fkey FOREIGN KEY (id_credito) REFERENCES public.ic_creditos(id_credito) ON DELETE RESTRICT;


--
-- Name: ic_polizas ic_polizas_id_socio_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_polizas
    ADD CONSTRAINT ic_polizas_id_socio_fkey FOREIGN KEY (id_socio) REFERENCES public.ic_socios(idsocio);


--
-- Name: ic_preferencial ic_preferencial_idsocio_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_preferencial
    ADD CONSTRAINT ic_preferencial_idsocio_fkey FOREIGN KEY (idsocio) REFERENCES public.ic_socios(idsocio) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: ic_situacion_bancaria_detalle ic_situacion_bancaria_detalle_transaccion_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_situacion_bancaria_detalle
    ADD CONSTRAINT ic_situacion_bancaria_detalle_transaccion_fkey FOREIGN KEY (transaccion) REFERENCES public.ic_situacion_bancaria(id_transaccion) ON DELETE CASCADE;


--
-- Name: ic_users ic_users_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ic_users
    ADD CONSTRAINT ic_users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id);


--
-- Name: ic_users Permitir lectura de perfiles a usuarios autenticados; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Permitir lectura de perfiles a usuarios autenticados" ON public.ic_users FOR SELECT TO authenticated USING (true);


--
-- Name: ic_aportes_semanales auth_delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_delete ON public.ic_aportes_semanales FOR DELETE TO authenticated USING (true);


--
-- Name: ic_bancos_logos auth_delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_delete ON public.ic_bancos_logos FOR DELETE TO authenticated USING (true);


--
-- Name: ic_creditos auth_delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_delete ON public.ic_creditos FOR DELETE TO authenticated USING (true);


--
-- Name: ic_creditos_ahorro auth_delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_delete ON public.ic_creditos_ahorro FOR DELETE TO authenticated USING (true);


--
-- Name: ic_creditos_amortizacion auth_delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_delete ON public.ic_creditos_amortizacion FOR DELETE TO authenticated USING (true);


--
-- Name: ic_creditos_documentos auth_delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_delete ON public.ic_creditos_documentos FOR DELETE TO authenticated USING (true);


--
-- Name: ic_creditos_garantes auth_delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_delete ON public.ic_creditos_garantes FOR DELETE TO authenticated USING (true);


--
-- Name: ic_creditos_historial auth_delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_delete ON public.ic_creditos_historial FOR DELETE TO authenticated USING (true);


--
-- Name: ic_creditos_pagos auth_delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_delete ON public.ic_creditos_pagos FOR DELETE TO authenticated USING (true);


--
-- Name: ic_creditos_precancelacion auth_delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_delete ON public.ic_creditos_precancelacion FOR DELETE TO authenticated USING (true);


--
-- Name: ic_gastos_administrativos auth_delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_delete ON public.ic_gastos_administrativos FOR DELETE TO authenticated USING (true);


--
-- Name: ic_polizas auth_delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_delete ON public.ic_polizas FOR DELETE TO authenticated USING (true);


--
-- Name: ic_polizas_pagos auth_delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_delete ON public.ic_polizas_pagos FOR DELETE TO authenticated USING (true);


--
-- Name: ic_preferencial auth_delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_delete ON public.ic_preferencial FOR DELETE TO authenticated USING (true);


--
-- Name: ic_situacion_bancaria auth_delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_delete ON public.ic_situacion_bancaria FOR DELETE TO authenticated USING (true);


--
-- Name: ic_situacion_bancaria_detalle auth_delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_delete ON public.ic_situacion_bancaria_detalle FOR DELETE TO authenticated USING (true);


--
-- Name: ic_socios auth_delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_delete ON public.ic_socios FOR DELETE TO authenticated USING (true);


--
-- Name: ic_solicitud_de_credito auth_delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_delete ON public.ic_solicitud_de_credito FOR DELETE TO authenticated USING (true);


--
-- Name: ic_users auth_delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_delete ON public.ic_users FOR DELETE TO authenticated USING (true);


--
-- Name: ic_aportes_semanales auth_insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_insert ON public.ic_aportes_semanales FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_bancos_logos auth_insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_insert ON public.ic_bancos_logos FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_creditos auth_insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_insert ON public.ic_creditos FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_creditos_ahorro auth_insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_insert ON public.ic_creditos_ahorro FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_creditos_amortizacion auth_insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_insert ON public.ic_creditos_amortizacion FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_creditos_documentos auth_insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_insert ON public.ic_creditos_documentos FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_creditos_garantes auth_insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_insert ON public.ic_creditos_garantes FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_creditos_historial auth_insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_insert ON public.ic_creditos_historial FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_creditos_pagos auth_insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_insert ON public.ic_creditos_pagos FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_creditos_precancelacion auth_insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_insert ON public.ic_creditos_precancelacion FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_gastos_administrativos auth_insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_insert ON public.ic_gastos_administrativos FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_polizas auth_insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_insert ON public.ic_polizas FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_polizas_pagos auth_insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_insert ON public.ic_polizas_pagos FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_preferencial auth_insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_insert ON public.ic_preferencial FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_situacion_bancaria auth_insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_insert ON public.ic_situacion_bancaria FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_situacion_bancaria_detalle auth_insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_insert ON public.ic_situacion_bancaria_detalle FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_socios auth_insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_insert ON public.ic_socios FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_solicitud_de_credito auth_insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_insert ON public.ic_solicitud_de_credito FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_users auth_insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_insert ON public.ic_users FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_aportes_semanales auth_select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_select ON public.ic_aportes_semanales FOR SELECT TO authenticated USING (true);


--
-- Name: ic_bancos_logos auth_select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_select ON public.ic_bancos_logos FOR SELECT TO authenticated USING (true);


--
-- Name: ic_creditos auth_select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_select ON public.ic_creditos FOR SELECT TO authenticated USING (true);


--
-- Name: ic_creditos_ahorro auth_select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_select ON public.ic_creditos_ahorro FOR SELECT TO authenticated USING (true);


--
-- Name: ic_creditos_amortizacion auth_select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_select ON public.ic_creditos_amortizacion FOR SELECT TO authenticated USING (true);


--
-- Name: ic_creditos_documentos auth_select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_select ON public.ic_creditos_documentos FOR SELECT TO authenticated USING (true);


--
-- Name: ic_creditos_garantes auth_select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_select ON public.ic_creditos_garantes FOR SELECT TO authenticated USING (true);


--
-- Name: ic_creditos_historial auth_select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_select ON public.ic_creditos_historial FOR SELECT TO authenticated USING (true);


--
-- Name: ic_creditos_pagos auth_select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_select ON public.ic_creditos_pagos FOR SELECT TO authenticated USING (true);


--
-- Name: ic_creditos_precancelacion auth_select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_select ON public.ic_creditos_precancelacion FOR SELECT TO authenticated USING (true);


--
-- Name: ic_gastos_administrativos auth_select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_select ON public.ic_gastos_administrativos FOR SELECT TO authenticated USING (true);


--
-- Name: ic_polizas auth_select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_select ON public.ic_polizas FOR SELECT TO authenticated USING (true);


--
-- Name: ic_polizas_pagos auth_select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_select ON public.ic_polizas_pagos FOR SELECT TO authenticated USING (true);


--
-- Name: ic_preferencial auth_select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_select ON public.ic_preferencial FOR SELECT TO authenticated USING (true);


--
-- Name: ic_situacion_bancaria auth_select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_select ON public.ic_situacion_bancaria FOR SELECT TO authenticated USING (true);


--
-- Name: ic_situacion_bancaria_detalle auth_select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_select ON public.ic_situacion_bancaria_detalle FOR SELECT TO authenticated USING (true);


--
-- Name: ic_socios auth_select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_select ON public.ic_socios FOR SELECT TO authenticated USING (true);


--
-- Name: ic_solicitud_de_credito auth_select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_select ON public.ic_solicitud_de_credito FOR SELECT TO authenticated USING (true);


--
-- Name: ic_users auth_select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_select ON public.ic_users FOR SELECT TO authenticated USING (true);


--
-- Name: ic_aportes_semanales auth_update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_update ON public.ic_aportes_semanales FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_bancos_logos auth_update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_update ON public.ic_bancos_logos FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_creditos auth_update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_update ON public.ic_creditos FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_creditos_ahorro auth_update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_update ON public.ic_creditos_ahorro FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_creditos_amortizacion auth_update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_update ON public.ic_creditos_amortizacion FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_creditos_documentos auth_update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_update ON public.ic_creditos_documentos FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_creditos_garantes auth_update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_update ON public.ic_creditos_garantes FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_creditos_historial auth_update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_update ON public.ic_creditos_historial FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_creditos_pagos auth_update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_update ON public.ic_creditos_pagos FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_creditos_precancelacion auth_update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_update ON public.ic_creditos_precancelacion FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_gastos_administrativos auth_update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_update ON public.ic_gastos_administrativos FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_polizas auth_update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_update ON public.ic_polizas FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_polizas_pagos auth_update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_update ON public.ic_polizas_pagos FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_preferencial auth_update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_update ON public.ic_preferencial FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_situacion_bancaria auth_update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_update ON public.ic_situacion_bancaria FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_situacion_bancaria_detalle auth_update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_update ON public.ic_situacion_bancaria_detalle FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_socios auth_update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_update ON public.ic_socios FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_solicitud_de_credito auth_update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_update ON public.ic_solicitud_de_credito FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_users auth_update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY auth_update ON public.ic_users FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_aportes_semanales; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ic_aportes_semanales ENABLE ROW LEVEL SECURITY;

--
-- Name: ic_bancos_logos; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ic_bancos_logos ENABLE ROW LEVEL SECURITY;

--
-- Name: ic_contratos; Type: ROW SECURITY; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.ic_contratos ENABLE ROW LEVEL SECURITY;

--
-- Name: ic_creditos; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ic_creditos ENABLE ROW LEVEL SECURITY;

--
-- Name: ic_creditos_ahorro; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ic_creditos_ahorro ENABLE ROW LEVEL SECURITY;

--
-- Name: ic_creditos_amortizacion; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ic_creditos_amortizacion ENABLE ROW LEVEL SECURITY;

--
-- Name: ic_creditos_documentos; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ic_creditos_documentos ENABLE ROW LEVEL SECURITY;

--
-- Name: ic_creditos_garantes; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ic_creditos_garantes ENABLE ROW LEVEL SECURITY;

--
-- Name: ic_creditos_historial; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ic_creditos_historial ENABLE ROW LEVEL SECURITY;

--
-- Name: ic_creditos_pagos; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ic_creditos_pagos ENABLE ROW LEVEL SECURITY;

--
-- Name: ic_creditos_precancelacion; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ic_creditos_precancelacion ENABLE ROW LEVEL SECURITY;

--
-- Name: ic_gastos_administrativos; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ic_gastos_administrativos ENABLE ROW LEVEL SECURITY;

--
-- Name: ic_polizas; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ic_polizas ENABLE ROW LEVEL SECURITY;

--
-- Name: ic_polizas_pagos; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ic_polizas_pagos ENABLE ROW LEVEL SECURITY;

--
-- Name: ic_preferencial; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ic_preferencial ENABLE ROW LEVEL SECURITY;

--
-- Name: ic_preferencial ic_preferencial_insert_auth; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY ic_preferencial_insert_auth ON public.ic_preferencial FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_preferencial ic_preferencial_select_auth; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY ic_preferencial_select_auth ON public.ic_preferencial FOR SELECT TO authenticated USING (true);


--
-- Name: ic_preferencial ic_preferencial_update_auth; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY ic_preferencial_update_auth ON public.ic_preferencial FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_services; Type: ROW SECURITY; Schema: public; Owner: supabase_admin
--

ALTER TABLE public.ic_services ENABLE ROW LEVEL SECURITY;

--
-- Name: ic_services ic_services_read_authenticated; Type: POLICY; Schema: public; Owner: supabase_admin
--

CREATE POLICY ic_services_read_authenticated ON public.ic_services FOR SELECT TO authenticated USING (true);


--
-- Name: ic_situacion_bancaria; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ic_situacion_bancaria ENABLE ROW LEVEL SECURITY;

--
-- Name: ic_situacion_bancaria_detalle; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ic_situacion_bancaria_detalle ENABLE ROW LEVEL SECURITY;

--
-- Name: ic_socios; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ic_socios ENABLE ROW LEVEL SECURITY;

--
-- Name: ic_socios ic_socios_insert_authenticated; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY ic_socios_insert_authenticated ON public.ic_socios FOR INSERT TO authenticated WITH CHECK (true);


--
-- Name: ic_socios ic_socios_select_authenticated; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY ic_socios_select_authenticated ON public.ic_socios FOR SELECT TO authenticated USING (true);


--
-- Name: ic_socios ic_socios_update_authenticated; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY ic_socios_update_authenticated ON public.ic_socios FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


--
-- Name: ic_solicitud_de_credito; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ic_solicitud_de_credito ENABLE ROW LEVEL SECURITY;

--
-- Name: ic_users; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.ic_users ENABLE ROW LEVEL SECURITY;

--
-- Name: TABLE ic_aportes_semanales; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ic_aportes_semanales TO anon;
GRANT ALL ON TABLE public.ic_aportes_semanales TO authenticated;
GRANT ALL ON TABLE public.ic_aportes_semanales TO service_role;


--
-- Name: TABLE ic_bancos_logos; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ic_bancos_logos TO anon;
GRANT ALL ON TABLE public.ic_bancos_logos TO authenticated;
GRANT ALL ON TABLE public.ic_bancos_logos TO service_role;


--
-- Name: SEQUENCE ic_bancos_logos_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.ic_bancos_logos_id_seq TO anon;
GRANT ALL ON SEQUENCE public.ic_bancos_logos_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.ic_bancos_logos_id_seq TO service_role;


--
-- Name: TABLE ic_contratos; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.ic_contratos TO postgres;
GRANT ALL ON TABLE public.ic_contratos TO anon;
GRANT ALL ON TABLE public.ic_contratos TO authenticated;
GRANT ALL ON TABLE public.ic_contratos TO service_role;


--
-- Name: TABLE ic_creditos; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ic_creditos TO anon;
GRANT ALL ON TABLE public.ic_creditos TO authenticated;
GRANT ALL ON TABLE public.ic_creditos TO service_role;


--
-- Name: TABLE ic_creditos_ahorro; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ic_creditos_ahorro TO anon;
GRANT ALL ON TABLE public.ic_creditos_ahorro TO authenticated;
GRANT ALL ON TABLE public.ic_creditos_ahorro TO service_role;


--
-- Name: TABLE ic_creditos_amortizacion; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ic_creditos_amortizacion TO anon;
GRANT ALL ON TABLE public.ic_creditos_amortizacion TO authenticated;
GRANT ALL ON TABLE public.ic_creditos_amortizacion TO service_role;


--
-- Name: TABLE ic_creditos_documentos; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ic_creditos_documentos TO anon;
GRANT ALL ON TABLE public.ic_creditos_documentos TO authenticated;
GRANT ALL ON TABLE public.ic_creditos_documentos TO service_role;


--
-- Name: TABLE ic_creditos_garantes; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ic_creditos_garantes TO anon;
GRANT ALL ON TABLE public.ic_creditos_garantes TO authenticated;
GRANT ALL ON TABLE public.ic_creditos_garantes TO service_role;


--
-- Name: TABLE ic_creditos_historial; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ic_creditos_historial TO anon;
GRANT ALL ON TABLE public.ic_creditos_historial TO authenticated;
GRANT ALL ON TABLE public.ic_creditos_historial TO service_role;


--
-- Name: TABLE ic_creditos_pagos; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ic_creditos_pagos TO anon;
GRANT ALL ON TABLE public.ic_creditos_pagos TO authenticated;
GRANT ALL ON TABLE public.ic_creditos_pagos TO service_role;


--
-- Name: TABLE ic_creditos_precancelacion; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ic_creditos_precancelacion TO anon;
GRANT ALL ON TABLE public.ic_creditos_precancelacion TO authenticated;
GRANT ALL ON TABLE public.ic_creditos_precancelacion TO service_role;


--
-- Name: TABLE ic_gastos_administrativos; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ic_gastos_administrativos TO anon;
GRANT ALL ON TABLE public.ic_gastos_administrativos TO authenticated;
GRANT ALL ON TABLE public.ic_gastos_administrativos TO service_role;


--
-- Name: TABLE ic_polizas; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ic_polizas TO anon;
GRANT ALL ON TABLE public.ic_polizas TO authenticated;
GRANT ALL ON TABLE public.ic_polizas TO service_role;


--
-- Name: TABLE ic_polizas_pagos; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ic_polizas_pagos TO anon;
GRANT ALL ON TABLE public.ic_polizas_pagos TO authenticated;
GRANT ALL ON TABLE public.ic_polizas_pagos TO service_role;


--
-- Name: TABLE ic_preferencial; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ic_preferencial TO authenticated;
GRANT ALL ON TABLE public.ic_preferencial TO service_role;


--
-- Name: TABLE ic_services; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON TABLE public.ic_services TO postgres;
GRANT ALL ON TABLE public.ic_services TO authenticated;
GRANT ALL ON TABLE public.ic_services TO service_role;


--
-- Name: SEQUENCE ic_services_id_seq; Type: ACL; Schema: public; Owner: supabase_admin
--

GRANT ALL ON SEQUENCE public.ic_services_id_seq TO postgres;
GRANT ALL ON SEQUENCE public.ic_services_id_seq TO anon;
GRANT ALL ON SEQUENCE public.ic_services_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.ic_services_id_seq TO service_role;


--
-- Name: TABLE ic_situacion_bancaria; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ic_situacion_bancaria TO anon;
GRANT ALL ON TABLE public.ic_situacion_bancaria TO authenticated;
GRANT ALL ON TABLE public.ic_situacion_bancaria TO service_role;


--
-- Name: TABLE ic_situacion_bancaria_detalle; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ic_situacion_bancaria_detalle TO anon;
GRANT ALL ON TABLE public.ic_situacion_bancaria_detalle TO authenticated;
GRANT ALL ON TABLE public.ic_situacion_bancaria_detalle TO service_role;


--
-- Name: TABLE ic_socios; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ic_socios TO anon;
GRANT ALL ON TABLE public.ic_socios TO authenticated;
GRANT ALL ON TABLE public.ic_socios TO service_role;


--
-- Name: TABLE ic_solicitud_de_credito; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ic_solicitud_de_credito TO anon;
GRANT ALL ON TABLE public.ic_solicitud_de_credito TO authenticated;
GRANT ALL ON TABLE public.ic_solicitud_de_credito TO service_role;


--
-- Name: TABLE ic_users; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.ic_users TO anon;
GRANT ALL ON TABLE public.ic_users TO authenticated;
GRANT ALL ON TABLE public.ic_users TO service_role;


--
-- PostgreSQL database dump complete
--

